packages:
  - "plugin/app"
  - "worker"
allowBuilds:
  '@parcel/watcher': true
  core-js: false
  core-js-pure: false
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  unrs-resolver: false
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260916.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260916.1'
  - '@cloudflare/workerd-linux-64@1.20260916.1'
  - '@cloudflare/workerd-linux-arm64@1.20260916.1'
  - '@cloudflare/workerd-windows-64@1.20260916.1'
  - miniflare@5.20260916.0-alpha
  - workerd@1.20260916.1
  - wrangler@4.133.0
  - '@cloudflare/workers-types@5.20260916.1'
